---
- name: Instalação e Parametrização Otimizada do PostgreSQL 17
  hosts: db_postgres_novo
  gather_facts: true
  tasks:
    - name: Instalar dependências iniciais do APT
      ansible.builtin.apt:
        name:
          - gnupg2
          - wget
        state: present
        update_cache: true

    # MÉTODOS MODERNOS PARA SUBSTITUIR O APT-KEY DEPRECIADO NO UBUNTU 26.04
    - name: Garantir que o diretório keyrings existe
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Importar a chave oficial de criptografia do PostgreSQL (Moderno)
      ansible.builtin.get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /etc/apt/keyrings/postgresql.asc
        mode: '0644'

    - name: Adicionar o repositório oficial do PostgreSQL ao sistema
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/postgresql.asc] http://apt.postgresql.org/pub/repos/apt {{ ansible_facts['distribution_release'] }}-pgdg main"
        state: present

    - name: Instalar o servidor PostgreSQL 17 e a biblioteca python3-psycopg2
      ansible.builtin.apt:
        name:
          - postgresql-17
          - python3-psycopg2
        state: present
        update_cache: true

    - name: Configurar o PostgreSQL para escutar conexões de rede externas
      ansible.builtin.lineinfile:
        path: /etc/postgresql/17/main/postgresql.conf
        regexp: '^#?listen_addresses\s*='
        line: "listen_addresses = '*'"
        state: present
      notify: Restart PostgreSQL

    - name: Configurar o pg_hba.conf para aceitar conexões vindas da rede interna do Swarm
      ansible.builtin.lineinfile:
        path: /etc/postgresql/17/main/pg_hba.conf
        line: "host    all             all             10.0.39.0/24            md5"
        state: present
      notify: Restart PostgreSQL

    - name: Garantir que o serviço do PostgreSQL está ativo no sistema
      ansible.builtin.systemd_service:
        name: postgresql
        state: started
        enabled: true

    # Força a aplicação imediata das configurações de escuta de conexões antes de criar o banco
    - name: Forçar o reinício do banco de dados (flush de handlers)
      ansible.builtin.meta: flush_handlers

    - name: Criar o usuário de acesso administrativo do PatchMon com a senha Nov@Senh@
      community.postgresql.postgresql_user:
        name: patchmon
        password: "Nov@Senh@"
        role_attr_flags: SUPERUSER
      become_user: postgres

    - name: Criar a base de dados patchmondb associada ao usuário
      community.postgresql.postgresql_db:
        name: patchmondb
        owner: patchmon
      become_user: postgres

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted
