- name: Instalar dependências iniciais do APT (Incluindo postgresql-common)
      ansible.builtin.apt:
        name:
          - gnupg2
          - wget
          - ca-certificates
          - apt-transport-https
          - postgresql-common  # <-- Pacote oficial que contém o script de bootstrap
        state: present
        update_cache: true

    - name: Remover arquivos antigos e obsoletos de repositórios do PostgreSQL para evitar conflitos
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/pgdg.list
        - /etc/apt/sources.list.d/postgresql.list

    # CURA DEFINITIVA: O script oficial cuida de registrar a chave e o repositório exato para o S.O.
    - name: Configurar o repositório oficial da PGDG de forma automatizada e nativa
      ansible.builtin.command: /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
      register: pg_setup_script
      changed_when: true

    - name: Atualizar o cache de pacotes (apt update)
      ansible.builtin.apt:
        update_cache: true

    - name: Instalar o servidor PostgreSQL 17 e bibliotecas de conexão Python
      ansible.builtin.apt:
        name:
          - postgresql-17
          - python3-psycopg2
        state: present

