---
- name: Preparação Física, Discos e Rede da VM Postgres
  hosts: db_postgres
  gather_facts: true
  tasks:
    - name: Alterar o hostname do sistema operacional
      ansible.builtin.hostname:
        name: postgresql-server

    - name: Atualizar o arquivo /etc/hosts com o novo hostname
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 postgresql-server"
        state: present

    - name: Gravar as configurações do IP definitivo no Netplan
      ansible.builtin.copy:
        dest: /etc/netplan/00-installer-config.yaml
        content: |
          network:
            version: 2
            ethernets:
              ens18:
                addresses:
                  - 10.0.39.41/24
                routes:
                  - to: default
                    via: 10.0.39.1
                nameservers:
                    addresses: [10.0.39.21, 10.0.39.26]
                    search: [nverse.local]
        mode: '0600'

    - name: Deletar o arquivo conflitante 50-cloud-init.yaml
      ansible.builtin.file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent

    - name: Criar a tabela de partição GPT no disco virtual de 100 GB (/dev/vdb)
      community.general.parted:
        device: /dev/vdb
        number: 1
        label: gpt
        state: present
        fs_type: ext4

    - name: Sincronizar tabela de partições com o kernel (Evita erro de Device /dev/vdb1 not found)
      ansible.builtin.shell: |
        partprobe /dev/vdb || true
        udevadm settle
      changed_when: false

    - name: Formatar a partição /dev/vdb1 com sistema de arquivos ext4
      community.general.filesystem:
        fstype: ext4
        dev: /dev/vdb1

    - name: Criar a pasta de dados nativa para o PostgreSQL
      ansible.builtin.file:
        path: /var/lib/postgresql
        state: directory
        mode: '0755'

    - name: Adicionar a montagem no fstab e montar a partição (/dev/vdb1)
      ansible.posix.mount:
        path: /var/lib/postgresql
        src: /dev/vdb1
        fstype: ext4
        opts: noatime,errors=remount-ro
        state: mounted

    - name: Reiniciar a VM para aplicar as alterações de IP, hostname e montagem
      ansible.builtin.reboot:
        reboot_timeout: 300
        msg: "Reboot disparado pelo Ansible Semaphore para aplicar novo IP 10.0.39.41"
