---
- name: Playbook de Exemplo Apache
  hosts: all
  become: true
  tasks:
    - name: Garantir que o Apache esteja instalado
      ansible.builtin.package:   # <--- Dois pontos obrigatórios aqui!
        name: apache2
        state: present 
