---
- name: Playbook de Exemplo NGINX
  hosts: all
  become: true
  tasks:
    - name: Garantir que o NGINX esteja instalado
      ansible.builtin.package:
        name: nginx
        state: present 
